# Generated by Django 5.2 on 2025-04-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
