# Generated by Django 5.1.5 on 2025-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
