# Generated by Django 5.1.5 on 2025-04-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_case_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(default='open', max_length=100),
        ),
    ]
